### ISSUE TITLE
NoClassDefFoundError: scala.collection.immutable.Nil$

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [pfn/android-sdk-plugin#149]
I have a multiproject build.

One project is a Java app called `libstest`, that uses a library project called `biblsinterface` made with Java, and it uses another library called `BiblS` made with Scala.

It compiles ok, but when running, I get this error:
```
java.lang.NoClassDefFoundError: scala.collection.immutable.Nil$
```
I've added this to the project config:
```scala
proguardOptions in Android += "-keep class scala.collection.immutable.Nil$",
```
but no success.

Here is an excerpt of my `Build.scala`:
```scala
	lazy val configComun = Seq(
		scalaVersion := "2.11.5",
		parallelExecution in Test := false,
		javacOptions ++= Seq("-encoding", "UTF-8"),
		platformTarget in Android := "android-19",
		typedResources in Android := false,
		sourcesInBase := false
	)

	/** Configuracion comun a todas las librerias. */
	lazy val configLib = android.Plugin.androidBuildAar ++ configComun ++ Seq(
		exportJars := true
	)

	/** Configuracion comun a todas las aplicaciones. */
	lazy val configApl = configComun ++ Seq(
		transitiveAndroidLibs in Android := false,
		proguardOptions in Android += proguardEstandar,
		packageRelease <<= packageRelease in Android,
		packageDebug <<= packageDebug in Android,
		run <<= run in Android,
		install <<= install in Android,
		javacOptions ++= Seq("-source", "1.7", "-target", "1.7"),
		javacOptions in Compile <<= (javacOptions in Compile) map {
			_ collect {
				case "1.5" => "1.7"
				case s => s
			}
		},
		// Al compilar tests, añadir el classpath normal
		managedClasspath in Test <++= (platformJars in Android, baseDirectory) map {
			case ((j, _), b) =>
				Seq(Attributed.blank(b / "bin" / "classes"), Attributed.blank(file(j)))
		},
		// Da problemas engordar .apk con librerias test
		debugIncludesTests in Android := false,
		dexMaxHeap in Android := "8192m",
	)

	/** Configuracion comun a todas las aplicaciones Scala. */
	lazy val configScala = configApl ++ Seq(
		//apkbuildExcludes in Android := true,
		//debugIncludesTests in Android := false,
		useProguard in Android := true,
		proguardOptions in Android += proguardScala,
		scalacOptions in Compile += "-feature",
		scalacOptions in(Compile, compile) ++= Seq(
			"-target:jvm-1.7"
		),
		proguardCache in Android ++= Seq(
			ProguardCache("org.scaloid") % "org.scaloid"
		),
		libraryDependencies ++= Seq(
			"org.scala-lang" % "scala-library" % scalaVersion.value,
			scaloid
		)
	)

	lazy val BiblS = project.settings(
		configLib ++ Seq(
			exportJars in Test := false,
			// https://github.com/pfn/android-sdk-plugin/issues/88
			sourceGenerators in Compile := Seq((sourceGenerators in Compile).value.last),
			// Hace falta para poder lanzar tests de Robolectric
			unmanagedClasspath in Test := ((builder in Android).value.getBootClasspath map Attributed.blank) ++ (unmanagedClasspath in Test).value,
			// Si no lo hacemos tendremos este problema: https://groups.google.com/forum/#!topic/scala-on-android/Z4aUbYBYrE4
			fork in Test := true,
			libraryDependencies ++= Seq(
				scaloid,
				support
			),
		): _*
	)

	lazy val biblsinterface = project.androidBuildWith(BiblS).settings(
		configLib ++ Seq(
		): _*
	)

	lazy val libstest = project.androidBuildWith(biblsinterface).settings(
		configScala ++ Seq(
			proguardOptions in Android += "-keep class scala.collection.immutable.Nil$",
				libraryDependencies ++= Seq(
				"com.android.support" % "support-v4" % "19.1.0",
				"com.android.support" % "recyclerview-v7" % "21.0.3"
			)
		): _*
	)
```

**Comment by pfn** [comment]
Need 2 pieces of debugging info:

1. Logcat messages from this error, particularly the lines before the exception, usually there are many dalvikvm messages

2. Run dexdump on the libstest project's classes.dex, verify that the Nil$ class is indeed included.

**Comment by DavidPerezIngeniero** [comment]
Thanks perry!

With `dexdump`, I can see references to `Nil$`, but this class isn't included:
```
   #5              : (in Les/fcc/bibl/bd/sincr/TablaCargaBlobsSincr;)
      name          : 'ddlIndices'
      type          : '()Lscala/collection/immutable/Nil$;'
      access        : 0x0001 (PUBLIC)
      code          -
      registers     : 3
      ins           : 1
      outs          : 0
      insns size    : 5 16-bit code units
      catches       : (none)
      positions     : 
        0x0000 line=98
      locals        : 
        0x0001 - 0x0004 reg=0 this Les/fcc/bibl/bd/sincr/TablaCargaBlobsSincr; 
        0x0000 - 0x0005 reg=2 this Les/fcc/bibl/bd/sincr/TablaCargaBlobsSincr; 
```

Here  is a more complete traces from `LogCat`:
```
03-03 11:40:36.095  28197-28197/? E/dalvikvm﹕ Could not find class 'com.example.admincliente.biblsinterface.BiblSInterface$2', referenced from method com.example.admincliente.biblsinterface.BiblSInterface.initData
03-03 11:40:36.225  28197-28197/? E/dalvikvm﹕ Could not find class 'com.example.admincliente.biblsinterface.BiblSInterface$1', referenced from method com.example.admincliente.biblsinterface.BiblSInterface.initTipologies
03-03 11:40:36.335  28197-28197/? E/dalvikvm﹕ Could not find class 'scala.collection.immutable.StringOps', referenced from method es.fcc.bibl.bd.TablaBase.<init>
03-03 11:40:36.415  28197-28197/? E/dalvikvm﹕ Could not find class 'es.fcc.bibl.bd.TablaBase$$anonfun$columnasBlob$1', referenced from method es.fcc.bibl.bd.TablaBase.columnasBlob$lzycompute
03-03 11:40:36.575  28197-28197/? E/dalvikvm﹕ Could not find class 'es.fcc.bibl.bd.TablaBase$$anonfun$consulta$1', referenced from method es.fcc.bibl.bd.TablaBase.consulta
03-03 11:40:36.605  28197-28197/? E/dalvikvm﹕ Could not find class 'es.fcc.bibl.bd.TablaBase$$anonfun$crea$1', referenced from method es.fcc.bibl.bd.TablaBase.crea
03-03 11:40:36.615  28197-28197/? E/dalvikvm﹕ Could not find class 'scala.StringContext', referenced from method es.fcc.bibl.bd.TablaBase.crea
03-03 11:40:36.625  28197-28197/? E/dalvikvm﹕ Could not find class 'scala.StringContext', referenced from method es.fcc.bibl.bd.TablaBase.cuantos
03-03 11:40:36.645  28197-28197/? E/dalvikvm﹕ Could not find class 'scala.collection.mutable.StringBuilder', referenced from method es.fcc.bibl.bd.TablaBase.cuantos
03-03 11:40:36.675  28197-28197/? E/dalvikvm﹕ Could not find class 'es.fcc.bibl.bd.TablaBase$$anonfun$1', referenced from method es.fcc.bibl.bd.TablaBase.ddlCreacion
03-03 11:40:36.695  28197-28197/? E/dalvikvm﹕ Could not find class 'scala.collection.mutable.StringBuilder', referenced from method es.fcc.bibl.bd.TablaBase.ddlIndice
03-03 11:40:36.715  28197-28197/? E/dalvikvm﹕ Could not find class 'es.fcc.bibl.bd.TablaBase$$anonfun$3', referenced from method es.fcc.bibl.bd.TablaBase.ddlIndice
03-03 11:40:36.735  28197-28197/? E/dalvikvm﹕ Could not find class 'scala.StringContext', referenced from method es.fcc.bibl.bd.TablaBase.destruye
03-03 11:40:37.205  28197-28197/? E/dalvikvm﹕ Could not find class 'es.fcc.bibl.bd.TablaBase$$anonfun$registrador$1', referenced from method es.fcc.bibl.bd.TablaBase.registrador
03-03 11:40:37.395  28197-28197/? E/dalvikvm﹕ Could not find class 'scala.collection.mutable.StringBuilder', referenced from method es.fcc.bibl.traza.Trazable$class.evento
03-03 11:40:37.405  28197-28197/? E/dalvikvm﹕ Could not find class 'scala.collection.mutable.StringBuilder', referenced from method es.fcc.bibl.traza.Trazable$class.eventoTmp
03-03 11:40:37.545  28197-28197/? E/dalvikvm﹕ Could not find class 'scala.collection.mutable.StringBuilder', referenced from method es.fcc.bibl.bd.Soporte$class.leeLinea
03-03 11:40:37.575  28197-28197/? E/dalvikvm﹕ Could not find class 'scala.StringContext', referenced from method es.fcc.bibl.bd.Soporte$class.peta$1
03-03 11:40:37.675  28197-28197/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.example.admincliente.libstest, PID: 28197
    java.lang.NoClassDefFoundError: scala.collection.immutable.Nil$
            at es.fcc.bibl.bd.TablaBase.<init>(Tabla.scala:53)
            at es.fcc.bibl.bd.sincr.CTablaBaseSincronizada.<init>(TablaSincronizada.scala:79)
            at es.fcc.bibl.bd.sincr.TablaBaseSincronizadaJ.<init>(TablaBaseSincronizadaJ.java:8)
            at com.example.admincliente.biblsinterface.Sgigri.<init>(Sgigri.java:48)
            at com.example.admincliente.biblsinterface.Sgigri.<clinit>(Sgigri.java:15)
            at com.example.admincliente.biblsinterface.BiblSInterface.<init>(BiblSInterface.java:58)
            at com.example.admincliente.libstest.MainActivity.onCreate(MainActivity.java:78)
            at android.app.Activity.performCreate(Activity.java:5484)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2400)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2498)
            at android.app.ActivityThread.access$900(ActivityThread.java:179)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1324)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5641)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1288)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1104)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by pfn** [comment]
Since your consuming project is java, you must set `proguardScala in Android := true`

**Comment by DavidPerezIngeniero** [comment]
Thanks, now the problem is that some classes from the `BiblS` project cannot be found by `ProGuard`.  

If I add it as a dependence from the main project, then it complains with this message:
```
[error] (libstest/android:rGenerator) Error: more than one library with package name 'android.support.v7.appcompat'
[error] You can temporarily disable this error with android.enforceUniquePackageName=false
[error] However, this is temporary and will be enforced in 1.0
```

This is my setup:
```
	lazy val biblsinterface = project.dependsOn(BiblS).settings(
		configLib ++ Seq(
		): _*
	)

	lazy val libstest = project.androidBuildWith(biblsinterface, BiblS).settings(...)
```

This is a nightmare.

**Comment by pfn** [comment]
You must set transitiveAndroidLibs to false, it must be applied to every client project

**Comment by DavidPerezIngeniero** [comment]
Thanks, meanwhile, I've found another workaround:

```scala
	lazy val biblsinterface = project.dependsOn(BiblS).settings(
		configLib ++ Seq(
			libraryDependencies ++= Seq(
				(projectID in BiblS).value
			        exclude("com.android.support", "appcompat-v7")
			)
		): _*
	)
````

**Comment by DavidPerezIngeniero** [comment]
After solving the new ProGuard problems, I'm now getting the same error at runtime:  :-(

```
03-03 11:27:37.475  27347-27347/com.example.admincliente.libstest E/dalvikvm﹕ Could not find class 'com.example.admincliente.biblsinterface.BiblSInterface$2', referenced from method com.example.admincliente.biblsinterface.BiblSInterface.initData
03-03 11:27:37.515  27347-27347/com.example.admincliente.libstest E/dalvikvm﹕ Could not find class 'com.example.admincliente.biblsinterface.BiblSInterface$1', referenced from method com.example.admincliente.biblsinterface.BiblSInterface.initTipologies
03-03 11:27:37.635  27347-27347/com.example.admincliente.libstest E/dalvikvm﹕ Could not find class 'scala.collection.immutable.StringOps', referenced from method es.fcc.bibl.bd.TablaBase.<init>
03-03 11:27:37.705  27347-27347/com.example.admincliente.libstest E/dalvikvm﹕ Could not find class 'es.fcc.bibl.bd.TablaBase$$anonfun$columnasBlob$1', referenced from method es.fcc.bibl.bd.TablaBase.columnasBlob$lzycompute
03-03 11:27:37.875  27347-27347/com.example.admincliente.libstest E/dalvikvm﹕ Could not find class 'es.fcc.bibl.bd.TablaBase$$anonfun$consulta$1', referenced from method es.fcc.bibl.bd.TablaBase.consulta
03-03 11:27:37.905  27347-27347/com.example.admincliente.libstest E/dalvikvm﹕ Could not find class 'es.fcc.bibl.bd.TablaBase$$anonfun$crea$1', referenced from method es.fcc.bibl.bd.TablaBase.crea
03-03 11:27:37.915  27347-27347/com.example.admincliente.libstest E/dalvikvm﹕ Could not find class 'scala.StringContext', referenced from method es.fcc.bibl.bd.TablaBase.crea
03-03 11:27:37.925  27347-27347/com.example.admincliente.libstest E/dalvikvm﹕ Could not find class 'scala.StringContext', referenced from method es.fcc.bibl.bd.TablaBase.cuantos
03-03 11:27:37.935  27347-27347/com.example.admincliente.libstest E/dalvikvm﹕ Could not find class 'scala.collection.mutable.StringBuilder', referenced from method es.fcc.bibl.bd.TablaBase.cuantos
03-03 11:27:37.965  27347-27347/com.example.admincliente.libstest E/dalvikvm﹕ Could not find class 'es.fcc.bibl.bd.TablaBase$$anonfun$1', referenced from method es.fcc.bibl.bd.TablaBase.ddlCreacion
03-03 11:27:37.995  27347-27347/com.example.admincliente.libstest E/dalvikvm﹕ Could not find class 'scala.collection.mutable.StringBuilder', referenced from method es.fcc.bibl.bd.TablaBase.ddlIndice
03-03 11:27:38.015  27347-27347/com.example.admincliente.libstest E/dalvikvm﹕ Could not find class 'es.fcc.bibl.bd.TablaBase$$anonfun$3', referenced from method es.fcc.bibl.bd.TablaBase.ddlIndice
03-03 11:27:38.045  27347-27347/com.example.admincliente.libstest E/dalvikvm﹕ Could not find class 'scala.StringContext', referenced from method es.fcc.bibl.bd.TablaBase.destruye
03-03 11:27:38.435  27347-27347/com.example.admincliente.libstest E/dalvikvm﹕ Could not find class 'es.fcc.bibl.bd.TablaBase$$anonfun$registrador$1', referenced from method es.fcc.bibl.bd.TablaBase.registrador
03-03 11:27:38.615  27347-27347/com.example.admincliente.libstest E/dalvikvm﹕ Could not find class 'scala.collection.mutable.StringBuilder', referenced from method es.fcc.bibl.traza.Trazable$class.evento
03-03 11:27:38.625  27347-27347/com.example.admincliente.libstest E/dalvikvm﹕ Could not find class 'scala.collection.mutable.StringBuilder', referenced from method es.fcc.bibl.traza.Trazable$class.eventoTmp
03-03 11:27:38.715  27347-27347/com.example.admincliente.libstest E/dalvikvm﹕ Could not find class 'scala.collection.mutable.StringBuilder', referenced from method es.fcc.bibl.bd.Soporte$class.leeLinea
03-03 11:27:38.725  27347-27347/com.example.admincliente.libstest E/dalvikvm﹕ Could not find class 'scala.StringContext', referenced from method es.fcc.bibl.bd.Soporte$class.peta$1
03-03 11:27:38.875  27347-27347/com.example.admincliente.libstest E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.example.admincliente.libstest, PID: 27347
    java.lang.NoClassDefFoundError: scala.collection.immutable.Nil$
```

**Comment by DavidPerezIngeniero** [comment]
With this setup it works:

```
	lazy val biblsinterface = project.dependsOn(BiblS).settings(
		configLib ++ Seq(
			transitiveAndroidLibs in Android := false
		): _*
	)
	lazy val libstest = project.androidBuildWith(biblsinterface, BiblS).settings(
		configScala ++ Seq(
			proguardScala in Android := true,
			proguardOptions in Android +=
				"""-keepattributes Signature
				""".stripMargin,
			libraryDependencies ++= Seq(
				"org.scala-lang" % "scala-library" % scalaVersion.value,
				"com.android.support" % "support-v4" % "21.0.3",
				"com.android.support" % "recyclerview-v7" % "21.0.3"
			)
		): _*
	)
```
