### ISSUE TITLE
Signing apk fails

### ISSUE THREAD

**Issue by pligor** [pfn/android-sdk-plugin#176]
Getting the following exception when trying to execute `android:package-release`:
```
java.lang.RuntimeException: Error signing jar (exit code was 1.)
	at scala.sys.package$.error(package.scala:27)
	at sbt.SignJar$.execute(Pack.scala:69)
	at sbt.SignJar$.sign(Pack.scala:59)
	at android.Tasks$$anonfun$53$$anonfun$apply$61.apply(tasks.scala:782)
	at android.Tasks$$anonfun$53$$anonfun$apply$61.apply(tasks.scala:772)
	at scala.Option.map(Option.scala:145)
	at android.Tasks$$anonfun$53.apply(tasks.scala:772)
	at android.Tasks$$anonfun$53.apply(tasks.scala:766)
	at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:35)
	at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[error] (android:signRelease) Error signing jar (exit code was 1.)
```
The instructions for signing apks out of the box by setting `key.alias`, `key.store`, `key.store.password` and `key.store.type` does not seem to work out of the box for us.

One thing missing from configuration for sure is one password. (not getting a prompt in terminal either)
Is this `key.store.password` the keypass or the storepass?
And where to set the other password?

Thank you

**Comment by pfn** [comment]
key.alias.password

**Comment by pligor** [comment]
Thanks Perry it works!
