### ISSUE TITLE
yet another NoClassDefFoundError which seems to be very persistent (android lollipop)

### ISSUE THREAD

**Issue by pligor** [pfn/android-sdk-plugin#182]
Here is a test android project: [https://bitbucket.org/pligor/test-android-app](https://bitbucket.org/pligor/test-android-app)

I have tried many configurations, ones that made sense and others that didn't. Spent more than 5 hours reading more than 50 links about possible solutions yet the CaseClassParcelableTrait cannot be found in Android.  
The device I am using is Sony Xperia Z3 compact with Android version 5.0.2 (API 21)

I have implemented a trait trying to simplify creating Parcelable classes. Still haven't been able to test it.

Any ideas would be more than appreciated

Here is the logcat:
```
 17414         AndroidRuntime  E  FATAL EXCEPTION: main
 17414         AndroidRuntime  E  Process: com.pligor.testapp, PID: 17414
 17414         AndroidRuntime  E  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/pligor/myandroid/parcel/CaseClassParcelableTrait$;
 17414         AndroidRuntime  E  	at com.pligor.myandroid.parcel.CaseClassParcelableTrait.<clinit>(CaseClassParcelableTrait.scala)
 17414         AndroidRuntime  E  	at java.lang.reflect.Field.get(Native Method)
 17414         AndroidRuntime  E  	at java.lang.reflect.Field.get(Field.java:279)
 17414         AndroidRuntime  E  	at android.os.Parcel.readParcelableCreator(Parcel.java:2309)
 17414         AndroidRuntime  E  	at android.os.Parcel.readParcelable(Parcel.java:2270)
 17414         AndroidRuntime  E  	at android.os.Parcel.readValue(Parcel.java:2177)
 17414         AndroidRuntime  E  	at android.os.Parcel.readArrayMapInternal(Parcel.java:2510)
 17414         AndroidRuntime  E  	at android.os.BaseBundle.unparcel(BaseBundle.java:221)
 17414         AndroidRuntime  E  	at android.os.Bundle.getParcelable(Bundle.java:804)
 17414         AndroidRuntime  E  	at com.pligor.testapp.activities.TextActivity$$anon$1.onClick(TextActivity.scala:39)
 17414         AndroidRuntime  E  	at android.view.View.performClick(View.java:4832)
 17414         AndroidRuntime  E  	at android.view.View$PerformClick.run(View.java:19839)
 17414         AndroidRuntime  E  	at android.os.Handler.handleCallback(Handler.java:739)
 17414         AndroidRuntime  E  	at android.os.Handler.dispatchMessage(Handler.java:95)
 17414         AndroidRuntime  E  	at android.os.Looper.loop(Looper.java:211)
 17414         AndroidRuntime  E  	at android.app.ActivityThread.main(ActivityThread.java:5321)
 17414         AndroidRuntime  E  	at java.lang.reflect.Method.invoke(Native Method)
 17414         AndroidRuntime  E  	at java.lang.reflect.Method.invoke(Method.java:372)
 17414         AndroidRuntime  E  	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
 17414         AndroidRuntime  E  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
 17414         AndroidRuntime  E  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.pligor.myandroid.parcel.CaseClassParcelableTrait$" on path: DexPathList[[zip file 
                                  "/system/framework/android.test.runner.jar", zip file "/data/app/com.pligor.testapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.pligor.testap
                                  p-1/lib/arm, /vendor/lib, /system/lib]]
 17414         AndroidRuntime  E  	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
 17414         AndroidRuntime  E  	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
 17414         AndroidRuntime  E  	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
 17414         AndroidRuntime  E  	... 20 more
 17414         AndroidRuntime  E  	Suppressed: java.lang.ClassNotFoundException: com.pligor.myandroid.parcel.CaseClassParcelableTrait$
 17414         AndroidRuntime  E  		at java.lang.Class.classForName(Native Method)
 17414         AndroidRuntime  E  		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
 17414         AndroidRuntime  E  		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
 17414         AndroidRuntime  E  		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
 17414         AndroidRuntime  E  		... 21 more
 17414         AndroidRuntime  E  	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

**Comment by pfn** [comment]
Not a build plugin issue. You need to set the appropriate proguard rules.

--

**Comment by pligor** [comment]
Thanks for your swift reply

However isn't it strange that we have set the proguard rules like this:  
`-keep class com.pligor.myandroid.** { *; }`  
in order to include all libraries in com.pligor.myandroid package and still get this issue ?!

**Comment by pfn** [comment]
Inspect the output classes.dex and classes.proguard.jar to verify it is
present in the output. Also inspect all dalvikvm logcat messages for
relevant logs.

--

**Comment by pfn** [comment]
Needs more info, reopen if you have more info to provide.
