### ISSUE TITLE
Predex files collision in a multiproject setup

### ISSUE THREAD

**Issue by aafa** [pfn/android-sdk-plugin#205]
Having these preconditions
- multiproject
- multi-dex enabled
- predex cache in place

Changing anything in project library and do `run` results in exception 
```
java.lang.IllegalArgumentException: Source predex-libraries/classes-fea1db6a2e85fdeda8f2073688c847728e688fa4.jar/classes.dex 
and destination predex-libraries/classes-fea1db6a2e85fdeda8f2073688c847728e688fa4.jar/classes.dex must be different
``` 

See full showcase
https://github.com/aafa/sbt-multiproject

Interestingly, doing `reload` + `run` (both each time) can make it work but not for long - I'm getting OutOfMemory exception after a while.

**Comment by pfn** [comment]
Presumably the OOM is in dex, increase dexMaxHeap

--

**Comment by pfn** [comment]
Thanks for the repro case, I'll take a look at fixing it next week.

--

**Comment by aafa** [comment]
`reload + run` - its just a workaround I discovered, it doesnt directly relate to the issue.

**Comment by aafa** [comment]
Now i get this exception. Same project, same steps.
plugin ver 1.4.13

```
 FATAL EXCEPTION: main
    Process: com.test.app, PID: 5214
    java.lang.RuntimeException: Unable to instantiate application com.test.core.AppContext: java.lang.ClassNotFoundException: Didn't find class "com.test.core.AppContext" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.test.app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.test.app-1/lib/x86, /vendor/lib, /system/lib]]
            at android.app.LoadedApk.makeApplication(LoadedApk.java:563)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4491)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.test.core.AppContext" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.test.app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.test.app-1/lib/x86, /vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at android.app.Instrumentation.newApplication(Instrumentation.java:979)
            at android.app.LoadedApk.makeApplication(LoadedApk.java:558)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4491)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
    Suppressed: java.lang.ClassNotFoundException: com.test.core.AppContext
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 13 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

**Comment by pfn** [comment]
Your main dex list is incorrect. Remove that setting and let it auto
generate.

--

**Comment by aafa** [comment]
Doing the same with auto generated main dex list

```
[info] Processing resources
[info] Packaging resources: resources-debug.ap_
[info] [debug] cache hit, skipping proguard!
[info] Generating maindexlist.txt
Note: there were 25 duplicate class definitions.
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [classes.jar:META-INF/MANIFEST.MF])
Error: Can't write [/private/tmp/mainDexClasses-40341.tmp.jar] (Can't read [/Users/aafa/Projects/github/sbt-multiproject/core/target/android-bin/classes.jar] (Duplicate zip entry [classes.jar:com/test/core/activity/CoreMainActivity.class]))
[error] failed to determine mainDexClasses
[error] (app/android:dexMainFileClassesListConfig) failed to determine mainDexClasses
[error] Total time: 4 s, completed 11.09.2015 18:39:46
```

> Your main dex list is incorrect

ok, but it worked under other conditions

**Comment by pfn** [comment]
Please try 1.4.14-SNAPSHOT (you'll need to publish-local) -- maindexlist
was still incorrect

**Comment by aafa** [comment]
With `addSbtPlugin("com.hanhuy.sbt" % "android-sdk-plugin" % "1.4.14-SNAPSHOT")`

```
> clean
[success] Total time: 0 s, completed 12.09.2015 12:44:06
> run
[info] Updating {file:/Users/aafa/Projects/github/sbt-multiproject/}app...

...

[info] Generating maindexlist.txt
[warn] Set mainDexClasses to improve build times:
[warn]   dexMainFileClassesConfig in Android := baseDirectory.value / "copy-of-maindexlist.txt"
[info] Generating dex, incremental=false, multidex=true
[info] dex method count: 6477
[info] Packaged: app-debug-unaligned.apk (1,21MB)
[info] Debug package does not need signing: app-debug-unaligned.apk
[info] zipaligned: app-debug.apk
...
[success] Total time: 19 s, completed 12.09.2015 12:44:26
> run
[info] Maintaining resource ID consistency
[warn] com.android.support:multidex:1.0.1 is not an explicit dependency, skipping
...
[info] Generating maindexlist.txt
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [com.android.support-multidex-1.0.1.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [com.hanhuy.android-protify-agent-0.6.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [classes.jar:META-INF/MANIFEST.MF])
[warn] Set mainDexClasses to improve build times:
[warn]   dexMainFileClassesConfig in Android := baseDirectory.value / "copy-of-maindexlist.txt"
[info] Pre-dexing: classes.jar
[info] Pre-dexing: com.android.support-multidex-1.0.1.jar
[info] Pre-dexing: com.hanhuy.android-protify-agent-0.6.jar
[info] Pre-dexing: proguard-cache-f55d320d9eb73ce7b895ac9c07017fd68730be7b.jar
[info] Generating dex, incremental=false, multidex=true
[info] dex method count: 229
...
[success] Total time: 13 s, completed 12.09.2015 12:44:43
> run
...
[info] Finding dependency references for: core:core:0.1-SNAPSHOT
[info] [debug] cache hit, skipping proguard!
[info] Generating maindexlist.txt
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [com.android.support-multidex-1.0.1.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [com.hanhuy.android-protify-agent-0.6.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [classes.jar:META-INF/MANIFEST.MF])
[warn] Set mainDexClasses to improve build times:
[warn]   dexMainFileClassesConfig in Android := baseDirectory.value / "copy-of-maindexlist.txt"
[info] Pre-dexing: classes.jar
[info] Generating dex, incremental=false, multidex=true
[info] dex method count: 229
...
[success] Total time: 8 s, completed 12.09.2015 12:44:55
``` 

On the last `run` I got same exception

```
java.lang.RuntimeException: Unable to instantiate application com.test.core.AppContext: java.lang.ClassNotFoundException: Didn't find class "com.test.core.AppContext" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.test.app-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
```

**Comment by pfn** [comment]
Odd, it worked fine for me on device

--

**Comment by dant3** [comment]
I see you have test.runner in your CP. Are you trying to run tests or actual application?

**Comment by aafa** [comment]
@pfn Have you tried with my project?
I tried again on device - same thing  see logs https://github.com/aafa/sbt-multiproject/tree/master/logs

@dant3 it's `run in Android` I dunno what test.runner is doing there

**Comment by dant3** [comment]
@aafa what device are you using?

**Comment by dant3** [comment]
nevermind I found in your logs

**Comment by dant3** [comment]
Not sure how exactly you building this, since on a second/third attempt to build your project I'm constantly seeing this problem:
```
Error: Can't read [/Users/dant3/Devel/test/sbt-multiproject/core/target/android-bin/classes.jar] (Can't process class [com/sbtmult/core/BuildConfig.class] (Unsupported class version number [52.0] (maximum 51.0, Java 1.7)))
```
Fixing your build like that:
```
--- a/project/TestBuild.scala
+++ b/project/TestBuild.scala
@@ -43,7 +43,8 @@ object TestBuild extends Build {
   lazy val commonSettings = Seq(
     scalaVersion := Versions.scalaVersion,
     platformTarget in Android := Versions.platformTarget,
-    minSdkVersion in Android := "21"
+    minSdkVersion in Android := "21",
+    scalacOptions += "-target:jvm-1.7"
   )
```

resolved the problem for me. Your example runs well on my HTC One M7 with Android 5.0.1.
I see you have multidex options, in particular class you trying to use is not in the main dex, however your app is not multidex app and you don't use support library. Perhaps you have a problematic device which does not treats multiple dex files for some reason? Could you try with different device/emulator and see if it works for you there?

**Comment by aafa** [comment]
> Perhaps you have a problematic device which does not treats multiple dex files for some reason?

It's not the case; device works fine with every other multidex app - gradle build, sbt with plugin of prev versions, even now first clean run works fine, the problem only appears on a second run.

> Could you try with different device/emulator and see if it works for you there?

I just tried on a freshly installed genymotion emulator. See updated logs https://github.com/aafa/sbt-multiproject/tree/master/logs

Notice that first run is fine 
```
09-14 05:54:01.769    3659-3685/system_process I/ActivityManager﹕ Displayed com.sbtmult.app/.activity.MainActivity: +294ms
```

And only second run falls with runtime exception
```
09-14 05:54:17.525    7515-7515/com.sbtmult.app E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.sbtmult.app, PID: 7515
    java.lang.RuntimeException: Unable to instantiate application com.sbtmult.core.AppContext
```

So as it turns out I see same runtime exception on 2 emulators and 1 device
```
> devices
[info]  Serial                 Model            Battery % Android Version
[info]  ---------------------- ---------------- --------- ---------------
[info]  87613303                MI 4W                  73% 5.0.2  API 21
[info]  192.168.56.101:5555    Google Nexus 4 - 5.0.0 - API 21 - 768x1280      100% 5.0    API 21
[info]  192.168.56.102:5555    Google Nexus 5 - 5.0.0 - API 21 - 1080x1920      100% 5.0    API 21
```

**Comment by dant3** [comment]
Hm. It turns out even after my changes with scalacOptions I can compile/run your project only for a first time. Trying to run your project for a second/third time results me in unable to compile:
```
Error: Can't read [/Users/dant3/Devel/test/sbt-multiproject/core/target/android-bin/classes.jar] (Can't process class [com/sbtmult/core/BuildConfig.class] (Unsupported class version number [52.0] (maximum 51.0, Java 1.7)))
```
Something definitively goes wrong with cache usage.

**Comment by pfn** [comment]
Set javacOptions, not scalacOptions. R and BuildConfig are java.

I still cannot reproduce the issue with the provided project.

Perform a dexdump on the generated dex files in your apk to identify what
I'd missing.

--

**Comment by pfn** [comment]
If a previous version worked, identify the last working version.

**Comment by dant3** [comment]
It looks like I am able to reproduce. To confirm. @aafa are you running on OS X?

**Comment by aafa** [comment]
@dant3 yes.

**Comment by aafa** [comment]
@pfn 
>If a previous version worked, identify the last working version.

I was referring to running multidex apps when talking about prev versions (having in mind that `reload + run` hack I mentioned early). Sorry to mislead you. 

I will do dexdump tomorrow morning.

**Comment by dant3** [comment]
Please try 1.4.14, it should be fixed there.

**Comment by aafa** [comment]
Confirm, it works.
@pfn @dant3  Thank you, guys!
