### ISSUE TITLE
Same aar dependency jar added twice

### ISSUE THREAD

**Issue by dant3** [pfn/android-sdk-plugin#214]
I have a project with multiple modules and using plugin version 1.5.5. My build definition:
https://github.com/dant3/ocular/blob/master/build.sbt

On first pass it fails with:
```
[error] (examples/android:proguard) java.io.IOException: Can't write [/Users/dant3/Devel/dant3/ocular/example/target/android/intermediates/proguard/classes.proguard.jar] (Can't read [/Users/dant3/Devel/dant3/ocular/core/target/android/intermediates/aars/com.android.support-support-v4-21.0.3/com.android.support-support-v4-21.0.3.jar(;;;;;;!META-INF/**,!rootdoc.txt)] (Duplicate zip entry [com.android.support-support-v4-21.0.3.jar:android/support/v4/widget/SlidingPaneLayout$SavedState$1.class]))
```

On second retry:
```
[info] classes.proguard.jar is up-to-date
[info] Creating proguard cache: proguard-cache-7e85f183f52086aa1bb18e4b840bd207c7bdbe1e.jar
[trace] Stack trace suppressed: run last examples/android:proguard for the full output.
[error] (examples/android:proguard) java.io.EOFException: Unexpected end of ZLIB input stream
```

What I see in the full log:
```
[debug] Filtering compile:dependency-classpath from: List(Attributed(/Users/dant3/Devel/dant3/ocular/core/target/android/intermediates/classes.jar), Attributed(/Users/dant3/Devel/dant3/ocular/example/target/android/intermediates/aars/com.android.support-support-v4-21.0.3/com.android.support-support-v4-21.0.3.jar), Attributed(/Users/dant3/Devel/dant3/ocular/example/target/android/intermediates/aars/com.android.support-support-v4-21.0.3/libs/internal_impl-21.0.3.jar), Attributed(/Users/dant3/Devel/dant3/ocular/core/target/android/intermediates/aars/com.android.support-support-v4-21.0.3/com.android.support-support-v4-21.0.3.jar), Attributed(/Users/dant3/Devel/dant3/ocular/core/target/android/intermediates/aars/com.android.support-support-v4-21.0.3/libs/internal_impl-21.0.3.jar), Attributed(/Users/dant3/Devel/dant3/ocular/example/target/android/intermediates/classes), Attributed(/Users/dant3/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.10.5.jar), Attributed(/Users/dant3/.ivy2/cache/com.lihaoyi/scalarx_2.10/jars/scalarx_2.10-0.2.8.jar), Attributed(/Users/dant3/.ivy2/cache/com.typesafe.akka/akka-actor_2.10/jars/akka-actor_2.10-2.3.14.jar), Attributed(/Users/dant3/.ivy2/cache/com.typesafe/config/bundles/config-1.2.1.jar), Attributed(/Users/dant3/Tools/android-sdk/extras/android/m2repository/com/android/support/support-annotations/22.2.0/support-annotations-22.2.0.jar))
[debug] classes.jar => Some(compile): Some(org.ocular:ocular-core:1.0.0)
[debug] com.android.support-support-v4-21.0.3.jar => None: None
[debug] internal_impl-21.0.3.jar => None: None
[debug] com.android.support-support-v4-21.0.3.jar => None: None
[debug] internal_impl-21.0.3.jar => None: None
[debug] classes => None: None
[debug] scala-library-2.10.5.jar => Some(compile-internal): Some(org.scala-lang:scala-library:2.10.5 ())
[debug] scalarx_2.10-0.2.8.jar => Some(compile-internal): Some(com.lihaoyi:scalarx_2.10:0.2.8)
[debug] akka-actor_2.10-2.3.14.jar => Some(compile-internal): Some(com.typesafe.akka:akka-actor_2.10:2.3.14)
[debug] config-1.2.1.jar => Some(compile-internal): Some(com.typesafe:config:1.2.1)
[debug] support-annotations-22.2.0.jar => Some(compile-internal): Some(com.android.support:support-annotations:22.2.0)
[debug] Jar uptodate: /Users/dant3/Devel/dant3/ocular/example/target/android/intermediates/classes.jar
[debug] Proguard cache rules: List(scala)
[info] classes.proguard.jar is up-to-date
[info] Creating proguard cache: proguard-cache-7e85f183f52086aa1bb18e4b840bd207c7bdbe1e.jar
java.io.EOFException: Unexpected end of ZLIB input stream
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:194)
	at java.util.jar.JarInputStream.read(JarInputStream.java:207)
	at java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:140)
	at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:118)
	at java.util.jar.JarInputStream.getNextEntry(JarInputStream.java:142)
	at java.util.jar.JarInputStream.getNextJarEntry(JarInputStream.java:179)
	at android.ProguardUtil$$anonfun$createCacheJar$2.apply(proguard.scala:30)
	at android.ProguardUtil$$anonfun$createCacheJar$2.apply(proguard.scala:30)
	at scala.collection.immutable.Stream$.continually(Stream.scala:1129)
	at scala.collection.immutable.Stream$$anonfun$continually$1.apply(Stream.scala:1129)
	at scala.collection.immutable.Stream$$anonfun$continually$1.apply(Stream.scala:1129)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
	at scala.collection.immutable.Stream$$anonfun$takeWhile$1.apply(Stream.scala:803)
	at scala.collection.immutable.Stream$$anonfun$takeWhile$1.apply(Stream.scala:803)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
	at scala.collection.immutable.Stream.filter(Stream.scala:472)
	at scala.collection.immutable.Stream$$anonfun$filteredTail$1.apply(Stream.scala:1149)
	at scala.collection.immutable.Stream$$anonfun$filteredTail$1.apply(Stream.scala:1149)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
	at scala.collection.immutable.Stream.foreach(Stream.scala:548)
	at android.ProguardUtil$.createCacheJar(proguard.scala:32)
	at android.Proguard$$anonfun$proguard$6.apply(proguard.scala:174)
	at android.Proguard$$anonfun$proguard$6.apply(proguard.scala:174)
	at scala.Option.foreach(Option.scala:236)
	at android.Proguard$.proguard(proguard.scala:173)
	at android.Tasks$$anonfun$74.apply(tasks.scala:1050)
	at android.Tasks$$anonfun$74.apply(tasks.scala:1048)
	at scala.Function9$$anonfun$tupled$1.apply(Function9.scala:35)
	at scala.Function9$$anonfun$tupled$1.apply(Function9.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (examples/android:proguard) java.io.EOFException: Unexpected end of ZLIB input stream
```

Looks like a bug, as same aar jars added twice, from different paths.

**Comment by pfn** [comment]
what is the output of `show example/android:aars` and `show example/android:transitiveAars`

**Comment by tek** [comment]
changing
```scala
  settings(androidBuild: _*).
  settings(commonSettings: _*).
  dependsOn(core).
```
to
```scala
  androidBuildWith(core).
  settings(commonSettings: _*).
```
fixes the problem.

**Comment by dant3** [comment]
Thanks, the ` androidBuildWith(core).` thing solved the problem.
