### ISSUE TITLE
FileNotFoundException when switching debug to release mode back and forth

### ISSUE THREAD

**Issue by aafa** [pfn/android-sdk-plugin#223]
Test to reproduce: https://github.com/aafa/android-sdk-plugin/commit/63f565f841123d50fdcb0f40b445f98eb8bfb7fe

```
[error] (gmroot/*:checkForProperties) java.io.FileNotFoundException: /private/var/folders/80/9jf8l5ss6bs46jtzjqnv0yq00000gn/T/sbt_7dcfcfc/multiproject-lib-with-resources/app/bin/intermediates/build_integration/app-BUILD-INTEGRATION.apk (No such file or directory)
```

**Comment by pfn** [comment]
What's the stack?

**Comment by pfn** [comment]
```scala
    if (r.getName.contains("-unsigned")) {

      s.log.warn("Package needs signing and zipaligning: " + r.getName)

      a.delete()

      r

    }
```

It's intentional when the package isn't signed. Not an issue.

**Comment by aafa** [comment]
You're right my test is incorrect. Sorry about that.
I've been noticing similar exception in my production build that happens from time to time when I switch from release to debug builds. I assumed that it has something to do with state sharing between builds but it's something else.

I'm still not sure what causing this, will keep observing.

```
com.android.builder.packaging.PackagerException: java.io.FileNotFoundException: /Users/aafa/Projects/aptekarsk/android/app/apps/pk/target/android/intermediates/packaging/resources-debug.ap_ does not exist
        at com.android.builder.internal.packaging.Packager.<init>(Packager.java:381)
        at com.android.builder.core.AndroidBuilder.packageApk(AndroidBuilder.java:1780)
        at android.Packaging$.apkbuild(Packaging.scala:60)
        at android.protify.Keys$$anonfun$protifySettings$14.apply(plugin.scala:196)
        at android.protify.Keys$$anonfun$protifySettings$14.apply(plugin.scala:184)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: /Users/aafa/Projects/aptekarsk/android/app/apps/pk/target/android/intermediates/packaging/resources-debug.ap_ does not exist
        at com.android.builder.internal.packaging.Packager.checkInputFile(Packager.java:768)
        at com.android.builder.internal.packaging.Packager.<init>(Packager.java:348)
        at com.android.builder.core.AndroidBuilder.packageApk(AndroidBuilder.java:1780)
        at android.Packaging$.apkbuild(Packaging.scala:60)
        at android.protify.Keys$$anonfun$protifySettings$14.apply(plugin.scala:196)
        at android.protify.Keys$$anonfun$protifySettings$14.apply(plugin.scala:184)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (pk/android:apkbuild) com.android.builder.packaging.PackagerException: java.io.FileNotFoundException: /Users/aafa/Projects/aptekarsk/android/app/apps/pk/target/android/intermediates/packaging/resources-debug.ap_ does not exist

```

**Comment by pfn** [comment]
Is the file present after the build fails? What is the full build log?

--

**Comment by pfn** [comment]
Also, the exception is not similar. One is a failure during apk packaging. The other is a false positive test case failure

**Comment by aafa** [comment]
So far haven't seen this bug again.

>Also, the exception is not similar

True. Thus
>You're right my test is incorrect. Sorry about that.
