### ISSUE TITLE
android-gradle-build wrong resource path

### ISSUE THREAD

**Issue by Ewg777** [pfn/android-sdk-plugin#224]
Hi, 
I'm trying to use protify but android-gradle-build generates wrong paths for res
```scala
      new ProjectLayout.Wrapped(ProjectLayout(baseDirectory.value)) {
        override def base = file(raw"""C:\d\app""")
        override def resources = file(raw"""C:\d\app\src\main\resources""")
...
        override def res = file(raw"""C:\d\app\src\main\res""")
```
I got this error:
```java
  at com.android.ide.common.process.ProcessResultImpl.assertNormalExitValue(ProcessResultImpl.java:45)
        at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:854)
        at android.Resources$.aapt(resources.scala:221)
        at android.Tasks$$anonfun$59$$anonfun$apply$71.apply(tasks.scala:887)
        at android.Tasks$$anonfun$59$$anonfun$apply$71.apply(tasks.scala:883)
        at android.Tasks$$anonfun$withCachedRes$1.apply(tasks.scala:898)
        at android.Tasks$$anonfun$withCachedRes$1.apply(tasks.scala:896)
        at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
```

How get to know what is exactly wrong?

**Comment by pfn** [comment]
How is it wrong? And always include the full error when submitting problem
reports.

--

**Comment by Ewg777** [comment]
@pfn so here is full error stack. What's wrong?
```java
[info] Packaging resources: resources-debug.ap_
[debug] All libs: List(AarLibrary(..... AarLibrary(C:\d\app\target\android\intermediates\aars\com.hanhuy.android-protify-agent-1.1.12))
[debug] packageForR: my.app.hidden
[debug] proguard.txt: C:\d\app\target\android\intermediates\proguard\proguard.txt
com.android.ide.common.process.ProcessException: Return code 1 for process 'C:\android_sdk\sdk\build-tools\23.0.2\aapt.exe package -f --no-crunch -I C:\android_sdk\sdk\platforms\android-23\android.jar -M C:\d\app\target\android\intermediates\manifest\AndroidManifest.xml -S C:\d\app\target\android\intermediates\res -A C:\d\app\target\android\intermediates\assets -m -J C:\d\app\target\android\generated\source -F C:\d\app\target\android\intermediates\packaging\resources-debug.ap_ -G C:\d\app\target\android\intermediates\proguard\proguard.txt --debug-mode --custom-package my.app.hidden -0 apk --output-text-symbols C:\d\app\target\android\generated\source'
        at com.android.ide.common.process.ProcessResultImpl.assertNormalExitValue(ProcessResultImpl.java:45)
        at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:854)
        at android.Resources$.aapt(resources.scala:221)
        at android.Tasks$$anonfun$45$$anonfun$apply$54.apply(tasks.scala:606)
        at android.Tasks$$anonfun$45$$anonfun$apply$54.apply(tasks.scala:601)
        at android.Tasks$$anonfun$withCachedRes$1.apply(tasks.scala:898)
        at android.Tasks$$anonfun$withCachedRes$1.apply(tasks.scala:896)
        at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
        at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:249)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:245)
        at sbt.Difference.apply(Tracked.scala:224)
        at sbt.Difference.apply(Tracked.scala:206)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:245)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:244)
        at sbt.Difference.apply(Tracked.scala:224)
        at sbt.Difference.apply(Tracked.scala:200)
        at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:244)
        at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:242)
        at android.Tasks$.withCachedRes(tasks.scala:899)
        at android.Tasks$$anonfun$45.apply(tasks.scala:601)
        at android.Tasks$$anonfun$45.apply(tasks.scala:596)
        at scala.Function11$$anonfun$tupled$1.apply(Function11.scala:35)
        at scala.Function11$$anonfun$tupled$1.apply(Function11.scala:34)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
[error] (app/android:packageResources) com.android.ide.common.process.ProcessException: Return code 1 for process 'C:\android_sdk\sdk\build-tools\23.0.2\aapt.exe package -f --no-crunch -I C:\android_sdk\sdk\platforms\android-23\android.jar -M C:\d\app\target\android\intermediates\manifest\AndroidManifest.xml -S C:\d\app\target\android\intermediates\res -A C:\d\app\target\android\intermediates\assets -m -J C:\d\app\target\android\generated\source -F C:\d\app\target\android\intermediates\packaging\resources-debug.ap_ -G C:\d\app\target\android\intermediates\proguard\proguard.txt --debug-mode --custom-package my.app.hidden -0 apk --output-text-symbols C:\d\app\target\android\generated\source'
```

**Comment by pfn** [comment]
Include the full error, not the output of last.

--

**Comment by Ewg777** [comment]
@pfn my post was updated

**Comment by pfn** [comment]
The error is missing google_maps_api_key. Where is it defined?

--

**Comment by Ewg777** [comment]
But your lib created it in 00-gradle-generated.sbt
```scala
).settings(
  buildTypes += ((raw"""debug""", List(
    TaskKey[scala.collection.Seq[scala.Tuple3[java.lang.String,java.lang.String,java.lang.String]]]("buildConfigOptions") in config("android") ++= Nil,
    TaskKey[scala.collection.Seq[scala.Tuple3[java.lang.String,java.lang.String,java.lang.String]]]("resValues") in config("android") ++= List((raw"""string""", raw"""google_maps_api_key""", raw"""234rtyadsuhijko""")),
    TaskKey[scala.collection.Seq[java.lang.String]]("proguardOptions") in config("android") ++= Nil,

```

**Comment by pfn** [comment]
The problem isn't incorrect resource path.

You must run the command "variant debug" when loading sbt.

--

**Comment by pfn** [comment]
https://github.com/pfn/android-sdk-plugin/blob/master/GRADLE.md#usage

See step 3

**Comment by Ewg777** [comment]
Great! Thanks! protify is awesome!
