### ISSUE TITLE
android:package only works the third time.

### ISSUE THREAD

**Issue by Richard-W** [pfn/android-sdk-plugin#226]

**Comment by Richard-W** [comment]
Sorry. I accidentally hit the submit button so the report has to be in this comment.

android:package only works when i issue it the third time.

Here is my build.sbt:
```scala
import android.Keys._

android.Plugin.androidBuild

name := "jenastop"

versionName := Some("1.3-SNAPSHOT")

versionCode := Some(9)

platformTarget in Android := "android-23"

minSdkVersion in Android := "15"

targetSdkVersion in Android := "23"

libraryDependencies ++= Seq(
  "com.android.support" % "appcompat-v7" % "23.1.0",
  "org.scala-lang.modules" %% "scala-xml" % "1.0.5"
)

scalaVersion := "2.11.7"

scalacOptions ++= Seq("-target:jvm-1.6", "-feature")

scalariformSettings
```
And here is the stack trace i'm am getting the first two times:

```
[info] Generating dex, incremental=false, multidex=false

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Exception parsing classes
	at com.android.dx.command.dexer.Main.processClass(Main.java:752)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:718)
	at com.android.dx.command.dexer.Main.access$1200(Main.java:85)
	at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1645)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:672)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:574)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)
Caused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
	at com.android.dx.command.dexer.Main.parseClass(Main.java:764)
	at com.android.dx.command.dexer.Main.access$1500(Main.java:85)
	at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1684)
	at com.android.dx.command.dexer.Main.processClass(Main.java:749)
	... 12 more
1 error; aborting
```

**Comment by pfn** [comment]
`javacOptions in Compile ++= Seq("-source", "1.7", "-target",  "1.7")`
