### ISSUE TITLE
Default debug.keystore is not found unless apkDebugSigningConfig is specified

### ISSUE THREAD

**Issue by aafa** [pfn/android-sdk-plugin#233]
Issue appears after 1.5.8 -> 1.5.9 update

```
[trace] Stack trace suppressed: run last sf/android:apkbuild for the full output.
[error] (sf/android:apkbuild) java.io.FileNotFoundException: /Users/aafa/.android/.android/.android/.android/.android/.android/.android/.android/debug.keystore (No such file or directory)
[error] Total time: 65 s, completed 03.12.2015 13:21:55
> last sf/android:apkbuild 
[debug] jars to process for resources: List(/Users/aafa/.ivy2/cache/com.fasterxml.jackson.core/jackson-databind/bundles/jackson-databind-2.5.0.jar, /Users/aafa/Projects/aptekarsk/android/app/core/target/android/intermediates/aars/com.android.support-support-v4-23.1.1/libs/internal_impl-23.1.1.jar, /Users/aafa/Projects/aptekarsk/android/app/core/target/android/intermediates/aars/com.android.support-support-v4-23.1.1/com.android.support-support-v4-23.1.1.jar, /Users/aafa/.ivy2/cache/com.thoughtworks.paranamer/paranamer/jars/paranamer-2.6.jar, /Users/aafa/Projects/aptekarsk/android/app/core/target/android/intermediates/aars/com.fortysevendeg-macroid-extras_2.11-0.2/com.fortysevendeg-macroid-extras_2.11-0.2.jar, /Users/aafa/.ivy2/cache/org.brianmckenna/wartremover_2.11/jars/wartremover_2.11-0.10.jar, /Users/aafa/Projects/aptekarsk/android/app/core/target/android/intermediates/aars/com.google.android.gms-play-services-gcm-8.1.0/com.google.android.gms-play-services-gcm-8.1.0.jar, /Users/aafa/Projects/aptekarsk/android/app/core/target/android/intermediates/aars/com.google.android.gms-play-services-maps-8.1.0/com.google.android.gms-play-services-maps-8.1.0.jar, /Users/aafa/.ivy2/cache/org.scala-lang.modules/scala-async_2.11/bundles/scala-async_2.11-0.9.2.jar, /Users/aafa/.ivy2/cache/org.scaloid/scaloid_2.11/jars/scaloid_2.11-3.6.1-10.jar, /Users/aafa/.ivy2/cache/com.google.code.gson/gson/jars/gson-2.3.1.jar, /Users/aafa/.ivy2/cache/bouncycastle/bcprov-jdk16/jars/bcprov-jdk16-140.jar, /Users/aafa/Projects/aptekarsk/android/app/apps/sf/target/android/intermediates/aars/com.hanhuy.android-protify-agent-1.1.13/com.hanhuy.android-protify-agent-1.1.13.jar, /Users/aafa/Projects/aptekarsk/android/app/core/target/android/intermediates/aars/com.instabug.library-instabugcore-1.2.1/libs/khandroid-httpclient-4.2.3.jar, /Users/aafa/Projects/aptekarsk/android/app/core/target/android/intermediates/aars/org.macroid-macroid_2.11-2.0.0-M4/org.macroid-macroid_2.11-2.0.0-M4.jar, /Users/aafa/Projects/aptekarsk/android/app/core/target/android/intermediates/aars/org.macroid-macroid-viewable_2.11-2.0.0-M4/org.macroid-macroid-viewable_2.11-2.0.0-M4.jar, /Users/aafa/Projects/aptekarsk/android/app/apps/sf/target/android/intermediates/protify/protify-descriptor.jar, /Users/aafa/Projects/aptekarsk/android/app/core/target/android/intermediates/aars/com.instabug.library-instabugsupport-1.2.1/com.instabug.library-instabugsupport-1.2.1.jar, /Users/aafa/Projects/aptekarsk/android/app/core/target/android/intermediates/aars/com.google.android.gms-play-services-basement-8.1.0/com.google.android.gms-play-services-basement-8.1.0.jar, /Users/aafa/Projects/aptekarsk/android/app/core/target/android/intermediates/classes.jar, /Users/aafa/Projects/aptekarsk/android/app/core/target/android/intermediates/aars/com.instabug.library-instabugcore-1.2.1/com.instabug.library-instabugcore-1.2.1.jar, /Users/aafa/.ivy2/cache/com.fasterxml.jackson.core/jackson-annotations/bundles/jackson-annotations-2.5.0.jar, /Users/aafa/.ivy2/cache/com.mcxiaoke.volley/library/jars/library-1.0.19.jar, /Users/aafa/.ivy2/cache/com.squareup.retrofit/retrofit/jars/retrofit-1.9.0.jar, /Users/aafa/.ivy2/cache/com.fasterxml.jackson.core/jackson-core/bundles/jackson-core-2.5.0.jar, /usr/local/Cellar/android-sdk/23.0.2/extras/android/m2repository/com/android/support/support-annotations/23.1.1/support-annotations-23.1.1.jar, /Users/aafa/Projects/aptekarsk/android/app/core/target/android/intermediates/aars/com.google.android.gms-play-services-base-8.1.0/com.google.android.gms-play-services-base-8.1.0.jar, /Users/aafa/Projects/aptekarsk/android/app/core/target/android/intermediates/aars/com.android.support-appcompat-v7-21.0.3/com.android.support-appcompat-v7-21.0.3.jar, /Users/aafa/.ivy2/cache/com.fasterxml.jackson.module/jackson-module-scala_2.11/bundles/jackson-module-scala_2.11-2.5.0.jar, /Users/aafa/Projects/aptekarsk/android/app/apps/sf/target/android/intermediates/protify/protify-dex.jar, /Users/aafa/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.1.jar, /Users/aafa/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.1.jar)
java.io.FileNotFoundException: /Users/aafa/.android/.android/.android/.android/.android/.android/.android/.android/debug.keystore (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at com.android.ide.common.signing.KeystoreHelper.getCertificateInfo(KeystoreHelper.java:209)
        at com.android.builder.core.AndroidBuilder.packageApk(AndroidBuilder.java:1836)
        at android.Packaging$.apkbuild(Packaging.scala:91)
        at android.protify.Keys$$anonfun$protifySettings$14.apply(plugin.scala:196)
        at android.protify.Keys$$anonfun$protifySettings$14.apply(plugin.scala:184)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (sf/android:apkbuild) java.io.FileNotFoundException: /Users/aafa/.android/.android/.android/.android/.android/.android/.android/.android/debug.keystore (No such file or directory)
```

Having ```apkDebugSigningConfig in Android := DebugSigningConfig()```  resolves issue.
Still, it should work without this being explicitly configured.

**Comment by pfn** [comment]
There must be a configuration error on your part, this does not occur
anywhere else.

--

**Comment by aafa** [comment]
I'm constantly having this cause in my head when facing any new bug - there must be something wrong with my config :) 
I will investigate it later, will reopen if I find anything specific
