### ISSUE TITLE
Cannot run in Android Studio

### ISSUE THREAD

**Issue by IgorGanapolsky** [pfn/android-sdk-plugin#237]
Hi,
I am trying to run a project in Android Studio.  I followed your directions in the README, and upon executing  `sbt ~android:run` I get this error:
> com.android.ide.common.process.ProcessException: Return code 1 for process '/Users/eazyigz/Library/Android/sdk/build-tools/23.0.2/aapt package -f --no-crunch -I /Users/eazyigz/Library/Android/sdk/platforms/android-23/android.jar -M /Users/eazyigz/git/square/u2020/target/android/intermediates/manifest/AndroidManifest.xml -S /Users/eazyigz/git/square/u2020/target/android/intermediates/res -A /Users/eazyigz/git/square/u2020/target/android/intermediates/assets -m -J /Users/eazyigz/git/square/u2020/target/android/generated/source -G /Users/eazyigz/git/square/u2020/target/android/intermediates/proguard/proguard.txt --debug-mode --custom-package com.jakewharton.u2020 -0 apk'
        at com.android.ide.common.process.ProcessResultImpl.assertNormalExitValue(ProcessResultImpl.java:45)
        at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:919)
        at android.Resources$.aapt(resources.scala:242)
        at android.Tasks$$anonfun$62$$anonfun$apply$71.apply(tasks.scala:892)
        at android.Tasks$$anonfun$62$$anonfun$apply$71.apply(tasks.scala:888)
        at android.Tasks$$anonfun$withCachedRes$1.apply(tasks.scala:903)
        at android.Tasks$$anonfun$withCachedRes$1.apply(tasks.scala:901)
        at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:186)
        at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:186)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:200)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:196)
        at sbt.Difference.apply(Tracked.scala:175)
        at sbt.Difference.apply(Tracked.scala:157)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:196)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:195)
        at sbt.Difference.apply(Tracked.scala:175)
        at sbt.Difference.apply(Tracked.scala:151)
        at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:195)
        at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:193)
        at android.Tasks$.withCachedRes(tasks.scala:904)
        at android.Tasks$$anonfun$62.apply(tasks.scala:888)
        at android.Tasks$$anonfun$62.apply(tasks.scala:879)
        at scala.Function11$$anonfun$tupled$1.apply(Function11.scala:35)
        at scala.Function11$$anonfun$tupled$1.apply(Function11.scala:34)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (android:rGenerator) com.android.ide.common.process.ProcessException: Return code 1 for process '/Users/eazyigz/Library/Android/sdk/build-tools/23.0.2/aapt package -f --no-crunch -I /Users/eazyigz/Library/Android/sdk/platforms/android-23/android.jar -M /Users/eazyigz/git/square/u2020/target/android/intermediates/manifest/AndroidManifest.xml -S /Users/eazyigz/git/square/u2020/target/android/intermediates/res -A /Users/eazyigz/git/square/u2020/target/android/intermediates/assets -m -J /Users/eazyigz/git/square/u2020/target/android/generated/source -G /Users/eazyigz/git/square/u2020/target/android/intermediates/proguard/proguard.txt --debug-mode --custom-package com.jakewharton.u2020 -0 apk'
[error] Total time: 0 s, completed Dec 6, 2015 8:32:09 PM

Please advise,
Igor

**Comment by pfn** [comment]
Always provide complete logs.

--
