### ISSUE TITLE
Issues when packaging with native code

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [pfn/android-sdk-plugin#244]
I have a project that uses a 3rd party native library.
As the project has some Scala code, ProGuard is always active.

- When using `android:packageDebug`, it creates a .apk which has inside a `classes.dex` with 1.6 Mb.  It fails.  Error message below.
- `android:packageRelease`, `classes.dex` with 1.6 Mb.  It fails also with same error.
- `android:run` sometimes creates an .apk much bigger `classes.dex` with 4 Mb, and it runs ok.

When it fails, this is the error:
```
java.lang.UnsatisfiedLinkError: readport
  at com.android.lflibs.serial_native.readport(Native Method)
  at com.android.lflibs.serial_native.ReadPort(serial_native.java:29)
```

I've checked the obvious:

- `lib*.so` are placed inside `lib/armeabi/` in `.apk`.
- The big version of `classes.dex` (4 Mb) has all methods of native class.  It runs ok.
- Smaller versions contain only used methods.
- Searching in [StackOverflow](stackoverflow.com) for related problems.  Gradle builds seem not to exhibit this behaviour.

Source code of serial_native:
```java
public class serial_native {
	private int fd;
	private int delay = 100;
	
	public int OpenComPort(String device)  {
             ....
	}
	
	public void CloseComPort() {
		closeport(fd);
	}
	
	public byte[] ReadPort(int count) {
		return readport(fd, count, delay);
	}
	
	public int WritePort(byte[] buf) {
		return writeport(fd, buf);
	}
	
	public void ClearBuffer() {
		clearportbuf(fd);
	}
	
	private native int openport(String port);						//open serial port
	private native void closeport(int fd);							//close serial port
	private native byte[] readport(int fd, int count, int delay);		//try to read number of count bytes, then return a byte array, which may be shorter than count
	private native int writeport(int fd, byte[] buf);					//try to write byte array to serialport, may be failed
	private native void clearportbuf(int fd);								//clear the serialport read/write buffer
	
	static {
		System.loadLibrary("package");
		System.loadLibrary("lfrfid");
	}
}
```

**Comment by pfn** [comment]
Include full logcat before and after the exception presents itself, not just filtered to the process. 

Compare the working native library vs the non working, are the symbols the same? 

Etc.

**Comment by pfn** [comment]
Compare the signatures of the working and non working serial_native class
using javap.

**Comment by DavidPerezIngeniero** [comment]
Full logcat output:
```
E/ACRA    ( 2477): es.fcc.incidences fatal error : readport
E/ACRA    ( 2477): java.lang.UnsatisfiedLinkError: readport
E/ACRA    ( 2477):      at com.android.lflibs.serial_native.readport(Native Method)
E/ACRA    ( 2477):      at com.android.lflibs.serial_native.ReadPort(serial_native.java:29)
E/ACRA    ( 2477):      at es.fcc.incidences.io.LectorRfid$$anon$1.run(LectorRfid.scala:30)
I/ACRA    ( 2477): Finishing the last Activity prior to killing the Process
I/ACRA    ( 2477): Finished class es.fcc.incidences.IncidenceDetailsActivity
I/Process ( 2477): Sending signal. PID: 2477 SIG: 9
I/ActivityManager( 1605): Process es.fcc.incidences (pid 2477) has died.
```

**Comment by pfn** [comment]
I said full logcat before and after. That is only the exception

**Comment by DavidPerezIngeniero** [comment]
Sorry.  This is the right info I think:
```
D/dalvikvm( 2477): Trying to load lib /data/data/es.fcc.incidences/lib/libpackage.so 0x41138038
D/dalvikvm( 2477): Added shared lib /data/data/es.fcc.incidences/lib/libpackage.so 0x41138038
D/dalvikvm( 2477): No JNI_OnLoad found in /data/data/es.fcc.incidences/lib/libpackage.so 0x41138038, skipping init
D/dalvikvm( 2477): Trying to load lib /data/data/es.fcc.incidences/lib/liblfrfid.so 0x41138038
D/dalvikvm( 2477): Added shared lib /data/data/es.fcc.incidences/lib/liblfrfid.so 0x41138038
I/lflibs_jni( 2477): JNI_OnLoad
E/dalvikvm( 2477): ERROR: couldn't find native method
E/dalvikvm( 2477): Requested: Lcom/android/lflibs/serial_native;.closeport:(I)V
E/lflibs_jni( 2477): Register real action failed com/android/lflibs/serial_native
E/lflibs_jni( 2477): ERROR: registerNatives failed
W/dalvikvm( 2477): JNI_OnLoad returned bad version (-1) in /data/data/es.fcc.incidences/lib/liblfrfid.so 0x41138038
E/PuertoSerie( 2477): No se puede cargar librerias nativas package y lfrfid: unknown failure
W/dalvikvm( 2477): No implementation found for native Lcom/android/lflibs/serial_native;.readport (III)[B
W/dalvikvm( 2477): threadid=11: thread exiting with uncaught exception (group=0x40a491f8)
```

**Comment by DavidPerezIngeniero** [comment]
The `serial_native#CloseComPort()` is missing and it isn't called from my code  So ProGuard removes it.  It must be called from native code.

**Comment by DavidPerezIngeniero** [comment]
Forcing my code to call `CloseComPort()` solves my issue.

The questions are:
- Why `android:run` and `android:packageDebug` provide different `.apk` files?  This is specific to `android-sdk-plugin`
- Why ProGuard isn't working?.  This question belongs to ProGuard and not to the plugin.

**Comment by pfn** [comment]
proguardCache, see #200

Set the proguard rule to keep your method as necessary.
